static char *rcsid="@(#) $Id: mail_utils.c,v 1.2 2010/03/31 05:15:55 root Exp $";
/*
 *  mail_utils.c
 *  fmtbckrep_xcode
 *
 *  Created by mark on 19/05/2009.
 *  Copyright 2009 Garetech Computer Solutions. All rights reserved.
 * $Log: mail_utils.c,v $
 * Revision 1.2  2010/03/31 05:15:55  root
 * mark
 *
 * Revision 1.1  2009/05/20 18:42:49  mark
 * Initial revision
 *
 */

#include "mail_utils.h"
#include "timefunc.h"


static char *version()
{
    return(rcsid);
}


int mailto(fio_t *mailfd, char *mailtoaddr, char *subject, int dbgflag)
{
    /* use sendmail -t to send a mime message based on fio_mailto->fnm
    */
    fio_t   *mailtmp;
    int	    err;
    char    boundary[512];
    
    if ((mailtmp = fio_open_temp("mailto", "xhtml" , MAX_BUF)) == (fio_t *) NULL ) {
	err=errno;
	fprintf(stderr, "Error opening temp file for mailtmp with extention %s %d:%s\n",  "xhtml" , err, strerror(err));
	return(-1);
    }
    mailtmp->debug = dbgflag;
    snprintf(boundary, sizeof(boundary), "%s.%lu",fio_basename(mailtmp), (lu_t) time((time_t *) NULL));

    fprintf(mailtmp->fd, "To: %s\n", mailtoaddr);
    fprintf(mailtmp->fd, "Subject: %s\n", subject);
    fprintf(mailtmp->fd, "Mime-Version: 1.0 (Generated by fmtbckrep_html)\n");
    /* fprintf(mailtmp->fd, "Content-Type: multipart/alternative; boundary=\"%s\"\n", boundary); */
    fprintf(mailtmp->fd, "Content-Type: multipart/mixed; boundary=\"%s\"\n", boundary);

    /* fprintf(mailtmp->fd, "\tboundary=\"%s\"\n", boundary ); */
    /* Content-Type: Multipart/Related; boundary=MIME_boundary; type=text/xml */
    
    /* fprintf(mailtmp->fd, "--%s\n", boundary);
    fprintf(mailtmp->fd, "Content-Type: text/plain; charset=US-ASCII\n");
    fprintf(mailtmp->fd, "Content-Transfer-Encoding: 7bit\n\n");
    fprintf(mailtmp->fd, "Backup summary messages in xhtml \"%s\"\n", subject); */
    
    fprintf(mailtmp->fd, "--%s\n", boundary);
    fprintf(mailtmp->fd, "Content-Type: text/html; charset=\"US-ASCII\"\n");
    fprintf(mailtmp->fd, "Content-Transfer-Encoding: 7bit\n\n");
    
    if (mailfd) {
	fio_fgets(mailfd);
	while(!feof(mailfd->fd)) {
	    fprintf(mailtmp->fd, "%s\n", mailfd->buf);
	    fio_fgets(mailfd);
	}
	fprintf(mailtmp->fd, "--%s\n", boundary);	    
	fio_close(mailtmp);
	
	snprintf(boundary, sizeof(boundary), "%s -t < %s\n", _PATH_SENDMAIL, mailtmp->fnm);
	system(boundary);
    } else {
	fprintf(stderr, "#BLIB:  Internal error null file descriptor\n");
	exit(EINVAL);
    }

    fio_close_and_free_unlink(&mailtmp);
    return(0);
}
