static char *rcsid="@(#) $Id: mail_utils.c,v 1.2 2011/04/11 03:53:46 mark Exp mark $";
/*
 *  mail_utils.c
 *  fmtbckrep_xcode
 *
 *  Created by mark on 19/05/2009.
 *  Copyright 2009 Garetech Computer Solutions. All rights reserved.
 * $Log: mail_utils.c,v $
 * Revision 1.2  2011/04/11 03:53:46  mark
 * add include log stuff
 *
 * Revision 1.1  2010/11/16 04:07:24  root
 * Initial revision
 *
 * Revision 1.2  2010/03/31 05:15:55  root
 * mark
 *
 * Revision 1.1  2009/05/20 18:42:49  mark
 * Initial revision
 *
 */

#include "mail_utils.h"
#include "timefunc.h"


static char *version()
{
    return(rcsid);
}


int mailto(files_t **mailfd_head, char *mailtoaddr, char *subject, int dbgflag, int include_flg)
{
    /* use sendmail -t to send a mime message based on fio_mailto->fnm
     */
    fio_t   *mailtmp;
    int	    err;
    char    boundary[512];
    files_t *mailfd;
    int     doattach;
    
    if ((mailtmp = fio_open_temp("mailto", "xhtml" , MAX_BUF)) == (fio_t *) NULL ) {
        err=errno;
        fprintf(stderr, "Error opening temp file for mailtmp with extention %s %d:%s\n",  "xhtml" , err, strerror(err));
        return(-1);
    }
    mailtmp->debug = dbgflag;
    snprintf(boundary, sizeof(boundary), "%s.%lu",fio_basename(mailtmp), (lu_t) time((time_t *) NULL));
    
    fprintf(mailtmp->fd, "To: %s\n", mailtoaddr);
    fprintf(mailtmp->fd, "Subject: %s\n", subject);
    fprintf(mailtmp->fd, "Mime-Version: 1.0 (Generated by blib)\n");
    /* fprintf(mailtmp->fd, "Content-Type: multipart/alternative; boundary=\"%s\"\n", boundary); */
    fprintf(mailtmp->fd, "Content-Type: multipart/mixed; boundary=\"----=%s\"\n\n", boundary);
    
    if (!mailfd_head || (mailfd_head && !*mailfd_head)) {
        fprintf(mailtmp->fd, "------=%s\n", boundary);
        fprintf(mailtmp->fd, "Content-Type: text/plain; charset=\"US-ASCII\"\n");
        fprintf(mailtmp->fd, "Content-Transfer-Encoding: 7bit\n\n");
        fprintf(mailtmp->fd, "Internal Error empty file list handed to mailto\n\n");
    } else {
        mailfd = *mailfd_head;
        while(mailfd) {
            doattach = 0;
            if (mailfd->optional_include) { // have we ask to consider these files optional ?
                if (include_flg) {
                    doattach = 1;
                } else {
                    doattach = 0;
                }
            } else {
                doattach = 1;
            }
            if (doattach) {
                if (mailfd->fio) {
                    attach_mime_file(&mailfd->fio, mailtmp, boundary);
                }
            }
            mailfd = mailfd->next;
        }
    }
    fprintf(mailtmp->fd, "------=%s--\n", boundary);
    fio_close(mailtmp);
    
    snprintf(boundary, sizeof(boundary), "%s -t < %s\n", _PATH_SENDMAIL, mailtmp->fnm);
    system(boundary);
    fio_close_and_free_unlink(&mailtmp);
    
    return(0);
}

int	attach_mime_file(fio_t **mailfd_ptr, fio_t *mailtmp, char *bounary_str)
{
    fio_t *mailfd;
    int	rval = 0;
    
    if (mailfd_ptr && *mailfd_ptr) {
        mailfd = *mailfd_ptr;
        fprintf(mailtmp->fd, "------=%s\n", bounary_str);
        fprintf(mailtmp->fd, "Content-Type: %s; charset=\"%s\"\n", mailfd->mimetype, mailfd->charset);
        fprintf(mailtmp->fd, "Content-Transfer-Encoding: %s\n\n", mailfd->encoding);
        
        if (mailfd) {
            fio_fgets(mailfd);
            while(!feof(mailfd->fd)) {
                fprintf(mailtmp->fd, "%s\n", mailfd->buf);
                fio_fgets(mailfd);
            }
            rval = mailfd->status;
            fio_close_and_free(mailfd_ptr);
        } else {
            fprintf(stderr, "#BLIB:  Internal error null file descriptor\n");
            exit(EINVAL);
        }
    }
    return(rval);
}
